language: python
python: 2.7
install: pip install -qq flake8 pytest pytest-cov tox
script:
  - py.test pingo -vrsx --cov pingo
after_success:
  - flake8 --version
  - flake8 --ignore=E501 pingo
  - pip install -qq coveralls
  - coveralls
